# Generated by Django 2.2.5 on 2020-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_auto_20200210_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='cpassword',
        ),
        migrations.RemoveField(
            model_name='register',
            name='number',
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
