# Generated by Django 2.2.5 on 2020-02-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
