# Generated by Django 2.2.5 on 2020-02-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200210_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(default='', max_length=250),
        ),
    ]
