# Generated by Django 2.2.5 on 2020-02-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200211_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movieid',
            field=models.IntegerField(default=''),
        ),
    ]
