# Generated by Django 2.2.5 on 2020-02-11 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_movieid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movieid',
        ),
    ]
