# Generated by Django 2.2.5 on 2020-02-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_usercomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usercomment',
        ),
    ]
