# Generated by Django 2.2.5 on 2020-02-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_delete_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_review',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
